[package]
name = "terminal_player"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
terminal_size = "0.1.17"
clap = "3.0.0-beta.4"
termion = "1.5.6"